/*
 * Copyright (c) 2020-2025, Sreeni Viswanadha <sreeni@viswanadha.net>.
 * Copyright (c) 2024-2025, Marc Mazas <mazas.marc@gmail.com>.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *     * Redistributions of source code must retain the above copyright notice,
 *       this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the names of the copyright holders nor the names of its
 *       contributors may be used to endorse or promote products derived from
 *       this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */
options
{
//  BUILD_PARSER = false;
//  BUILD_TOKEN_MANAGER = false;
//  JAVA_TEMPLATE_TYPE = "modern";
//  DEBUG_LOOKAHEAD = true;
//  DEBUG_PARSER = true;
  DEBUG_TOKEN_MANAGER = true;
  JAVA_UNICODE_ESCAPE = true;
//  KEEP_LINE_COLUMN = false;
//  NO_DFA=true;
//  PARSER_INCLUDE = "stdio.h";
//  TOKEN_INCLUDE = "<stdio.h>";
//  TOKEN_MANAGER_INCLUDE = "<stdio.h>";
//  SANITY_CHECK = false;
//  STATIC = false;

//  NAMESPACE = "mns";
}

PARSER_BEGIN(ComplexLineComment)
/* keep same number of lines as in the java version
   to get identical test results for Line:Column */





















































PARSER_END(ComplexLineComment)

SKIP : { " " | "\t" | "\n" | "\r" }

TOKEN :
{
   <#NA : ~[ "-", "\r", "\n" ] >
| <#EOL : ( "\n" | "\r" | "\r\n" ) >
| < INTEGER : ( ["0"-"9"] )+ >
}

SPECIAL_TOKEN :
{
  "--" : LineComment
}

< LineComment >
SPECIAL_TOKEN :
{
  < (
      < NA >
    | "-" < NA >
    )*
    (
      < EOL >
    | "-" < EOL >
    | "-" "-"
    )? > : DEFAULT
}

TOKEN :
{
  < Id : [ "a"-"z", "A"-"Z" ] ( [ "a"-"z", "A"-"Z", "0"-"9", "-" ] )* >
  { System.Console.Out.WriteLine(matchedToken.ToString()); }
}

void Input() :
{}
{
  ( <Id> )*
  // { System.Console.Out.WriteLine("Finished ID+"); System.Console.Error.WriteLine("Finished ID+"); }
  <EOF>
  // { System.Console.Out.WriteLine("EOF found"); System.Console.Error.WriteLine("EOF found"); }
}
