/*
 * Copyright (c) 2020-2025, Sreeni Viswanadha <sreeni@viswanadha.net>.
 * Copyright (c) 2024-2025, Marc Mazas <mazas.marc@gmail.com>.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *     * Redistributions of source code must retain the above copyright notice,
 *       this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the names of the copyright holders nor the names of its
 *       contributors may be used to endorse or promote products derived from
 *       this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */
options
{
//  BUILD_PARSER = false;
//  BUILD_TOKEN_MANAGER = false;
//  JAVA_TEMPLATE_TYPE = "modern";
  DEBUG_LOOKAHEAD = true;
  DEBUG_PARSER = true;
//  DEBUG_TOKEN_MANAGER = true;
//  JAVA_UNICODE_ESCAPE = true;
  KEEP_LINE_COLUMN = false;
  NO_DFA=true;
//  PARSER_INCLUDE = "stdio.h";
//  TOKEN_INCLUDE = "<stdio.h>";
//  TOKEN_MANAGER_INCLUDE = "<stdio.h>";
  SANITY_CHECK = false;
  STATIC = false;

  NAMESPACE = "mns";
}

PARSER_BEGIN(Bug)
/* no need to keep same number of lines as in the java version
   to get identical test results for Line:Column
   as option KEEP_LINE_COLUMN == false */

PARSER_END(Bug)

TOKEN_MGR_DECLS : {
  int my_tm_decl;
}

SKIP : { " " | "\t" | "\n" | "\r" }

TOKEN :
{
  < LBRACKET : "[" >
| < RBRACKET : "]" >
| < LBRACE : "{" >
| < RBRACE : "}" >
| < LPAREN : "(" >
| < RPAREN : ")" >
}

TOKEN :
{
  < #UPPER : ["A"-"Z"] > 
| < #LOWER : ["a"-"z"] > 
| < #DIGIT : ["0"-"9"] > 
| < NUMBER : ( "0" | ["1"-"9"] ( < DIGIT > )*) > 
| < #LOWERCASEFIRST : < LOWER > ( "-" ( < LOWER > | < UPPER > | < DIGIT > ) | ( < LOWER > | < UPPER > | < DIGIT > ) )* > 
| < #UPPERCASEFIRST : < UPPER > ( "-" ( < LOWER > | < UPPER > | < DIGIT > ) | ( < LOWER > | < UPPER > | < DIGIT > ) )* >
}

TOKEN :
{
  < IDENTIFIANT : < LOWERCASEFIRST > >
| < VALUEREFERENCE : < LOWERCASEFIRST > >
}
// e
/* ee */
/** eee */
void EnumerationItem() :
{}
{
  < LBRACE >
  (
    LOOKAHEAD(2)
    NamedNumber()
  | identifier()
  )
  < RBRACE >
}

// n

/** nnn */
void NamedNumber() :
{}
{
  (
    identifier()
  | valuereference()
  )
  < LPAREN > < NUMBER > < RPAREN >
}
// i
void identifier() :
{}
{
  < IDENTIFIANT >
}

void valuereference() :
{}
{
  < VALUEREFERENCE >
}
