<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (c) 2020-2025, Sreeni Viswanadha <sreeni@viswanadha.net>.
Copyright (c) 2024-2025, Marc Mazas <mazas.marc@gmail.com>.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the names of the copyright holders nor the names of its
      contributors may be used to endorse or promote products derived from
      this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
THE POSSIBILITY OF SUCH DAMAGE.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org</groupId>
    <artifactId>javacc</artifactId>
    <version>8.1.0-SNAPSHOT</version>
    <relativePath></relativePath>
  </parent>

  <groupId>org.javacc.generator.csharp</groupId>
  <artifactId>it</artifactId>
  <version>1.1.0-SNAPSHOT</version>
  <packaging>pom</packaging>

  <name>JavaCC C# code generator / it</name>

  <!--
       ment to be called by maven-invoker-plugin from javacc-8-c#/pom.xml,
       note: parent is javacc-8/pom.xml, not javacc-8-c#/pom.xml
       defines non herited settings (help) and specific settings (codeGenerator, profiles)
  -->

  <properties>
    <mojohaus.build-helper-maven-plugin.version>3.6.0</mojohaus.build-helper-maven-plugin.version>
<!--    <plexus-compiler-csharp.version>2.15.0</plexus-compiler-csharp.version>-->
    <plexus-compiler-csharp.version>2.15.1-SNAPSHOT</plexus-compiler-csharp.version>
  </properties>

  <build>
    <pluginManagement>

      <!-- all in parent javacc-8/pom.xml except the following ones -->

      <plugins>
        <plugin>
          <!-- processes JavaCC/JJTree grammar files;
               goals: javacc, jjtree-javacc, jjtree -->
          <groupId>org.javacc.plugin</groupId>
          <artifactId>javacc-maven-plugin</artifactId>
          <dependencies>
            <!-- uses v8 C:# generator; overriden in v7 profiles -->
            <dependency>
              <groupId>org.javacc.generator</groupId>
              <artifactId>csharp</artifactId>
              <version>${javacc.csharp.version}</version>
              <scope>runtime</scope>
            </dependency>
          </dependencies>
        </plugin>

        <plugin>
          <!-- assists the build lifecyle;
               here use goal add-source to add the csharp source folders -->
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>build-helper-maven-plugin</artifactId>
          <version>${mojohaus.build-helper-maven-plugin.version}</version>
        </plugin>

        <plugin>
          <!-- allows to compile C# code on different architectures with different compilers/linkers -->
          <!-- standard maven lifecycle -->
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>${maven-compiler-plugin.version}</version>
          <dependencies>
            <dependency>
              <groupId>org.codehaus.plexus</groupId>
              <artifactId>plexus-compiler-csharp</artifactId>
              <version>${plexus-compiler-csharp.version}</version>
            </dependency>
          </dependencies>
        </plugin>

      </plugins>
    </pluginManagement>

    <plugins>

      <plugin>
        <groupId>org.javacc.plugin</groupId>
        <artifactId>javacc-maven-plugin</artifactId>
        <configuration>
          <codeGenerator>c#</codeGenerator>
        </configuration>
      </plugin>

      <plugin>
        <!-- assists the build lifecyle; here use goal add-source to add the csharp source folders -->
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>add-source</id>
            <!-- after (javacc) generate-sources but before (javac) compile -->
            <phase>process-resources</phase>
            <goals>
              <goal>add-source</goal>
            </goals>
            <configuration>
              <sources>
                <source>src/main/csharp</source>
              </sources>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <!-- allows to compile C# code on different architectures with different compilers/linkers -->
        <!-- standard maven lifecycle -->
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <!-- setting compileSourceRoots to src/main/chsarp,target/gen.../csharp makes the plugin
             compile twice the .cs, in phases default-compile and default-testCompile to
             target/classes and target/test-classes; so used the build-helper-maven-plugin -->
          <compilerId>csharp</compilerId>
          <!-- unfortunately the build does not fail on errors... -->
          <failOnError>true</failOnError>
          <fork>true</fork>
          <verbose>true</verbose>
          <!-- compilerArguments raises a depecation warning but works, compilerArgs does not -->
          <compilerArguments>
            <nologo>true</nologo>
            <target>exe</target>
            <out>${project.artifactId}.exe</out>
            <!--  unfortunately compiler options PreferredUILang & Utf8Output not supported
            https://github.com/codehaus-plexus/plexus-compiler/blob/plexus-compiler-2.15.0/plexus-compilers/plexus-compiler-csharp/src/main/java/org/codehaus/plexus/compiler/csharp/CSharpCompiler.java-->
          </compilerArguments>
        </configuration>
      </plugin>

    </plugins>
  </build>

  <profiles>

    <profile>
      <id>Windows</id>
      <activation>
        <os>
          <family>Windows</family>
        </os>
      </activation>
      <properties>
        <suffix>exe</suffix>
      </properties>
    </profile>

    <profile>
      <id>Linux</id>
      <activation>
        <os>
          <family>Linux</family>
        </os>
      </activation>
      <properties>
        <suffix>sh</suffix>
      </properties>
    </profile>

    <profile>
      <id>MacOS</id>
      <activation>
        <os>
          <family>mac</family>
        </os>
      </activation>
      <properties>
        <suffix>sh</suffix>
      </properties>
    </profile>

    <profile>
      <!-- JJTree/JavaCC project compiled with JavaCC v8; implicitely activated -->
      <id>jjt8</id>
      <activation>
        <file>
          <exists>${basedir}/src/main/jjtree</exists>
        </file>
      </activation>
      <build>
        <plugins>
          <plugin>
            <groupId>org.javacc.plugin</groupId>
            <artifactId>javacc-maven-plugin</artifactId>
            <executions>
              <execution>
                <id>jjt8-jjt-jjc</id>
                <phase>generate-sources</phase>
                <goals>
                  <goal>jjtree-javacc</goal>
                </goals>
                <configuration>
                  <codeGenerator>c#</codeGenerator>
                  <sourceDirectory>src/main/jjtree</sourceDirectory>
                  <interimDirectory>target/generated-sources/jjtree</interimDirectory>
                  <outputDirectory>target/generated-sources/csharp</outputDirectory>
                  <nodeDirectory>src/main/csharp</nodeDirectory>
                </configuration>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>${maven-compiler-plugin.version}</version>
            <dependencies>
              <dependency>
                <groupId>org.codehaus.plexus</groupId>
                <artifactId>plexus-compiler-csharp</artifactId>
                <version>${plexus-compiler-csharp.version}</version>
              </dependency>
            </dependencies>
            <configuration>
              <compilerId>csharp</compilerId>
              <!--              <failOnError>false</failOnError>-->
              <fork>true</fork>
              <verbose>true</verbose>
              <!-- compilerArguments raises a depecation warning but works, compilerArgs does not -->
              <compilerArguments>
                <nologo>true</nologo>
                <target>exe</target>
                <out>${project.artifactId}.exe</out>
                <!--  unfortunately compiler options PreferredUILang & Utf8Output not supported
                https://github.com/codehaus-plexus/plexus-compiler/blob/plexus-compiler-2.15.0/plexus-compilers/plexus-compiler-csharp/src/main/java/org/codehaus/plexus/compiler/csharp/CSharpCompiler.java-->
              </compilerArguments>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>

    <profile>
      <!-- JavaCC project compiled with JavaCC v8; implicitely activated -->
      <id>jcc8</id>
      <activation>
        <file>
          <exists>${basedir}/src/main/javacc</exists>
        </file>
      </activation>
      <build>
        <pluginManagement>
          <plugins>
            <plugin>
              <groupId>org.javacc.plugin</groupId>
              <artifactId>javacc-maven-plugin</artifactId>
              <version>${javacc-maven-plugin.version}</version>
              <dependencies>
                <dependency>
                  <groupId>org.javacc.generator</groupId>
                  <artifactId>csharp</artifactId>
                  <version>${javacc.csharp.version}</version>
                  <scope>runtime</scope>
                </dependency>
              </dependencies>
            </plugin>
          </plugins>
        </pluginManagement>
        <plugins>
          <plugin>
            <groupId>org.javacc.plugin</groupId>
            <artifactId>javacc-maven-plugin</artifactId>
            <executions>
              <execution>
                <id>jcc8jcc</id>
                <phase>generate-sources</phase>
                <goals>
                  <goal>javacc</goal>
                </goals>
                <configuration>
                  <sourceDirectory>src/main/javacc</sourceDirectory>
                  <outputDirectory>target/generated-sources/csharp</outputDirectory>
                </configuration>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <dependencies>
              <dependency>
                <groupId>org.codehaus.plexus</groupId>
                <artifactId>plexus-compiler-csharp</artifactId>
                <version>${plexus-compiler-csharp.version}</version>
              </dependency>
            </dependencies>
            <configuration>
              <compilerId>csharp</compilerId>
              <!--              <failOnError>false</failOnError>-->
              <fork>true</fork>
              <verbose>true</verbose>
              <!-- compilerArguments raises a depecation warning but works, compilerArgs does not -->
              <compilerArguments>
                <nologo>true</nologo>
                <target>exe</target>
                <out>${project.artifactId}.exe</out>
                <!--  unfortunately compiler options PreferredUILang & Utf8Output not supported
                https://github.com/codehaus-plexus/plexus-compiler/blob/plexus-compiler-2.15.0/plexus-compilers/plexus-compiler-csharp/src/main/java/org/codehaus/plexus/compiler/csharp/CSharpCompiler.java-->
              </compilerArguments>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>

    <profile>
      <id>jjt8w</id>
      <build>
        <pluginManagement>
          <plugins>
            <plugin>
              <groupId>org.javacc.plugin</groupId>
              <artifactId>javacc-maven-plugin</artifactId>
              <dependencies>
                <dependency>
                  <groupId>org.javacc.generator</groupId>
                  <artifactId>csharp</artifactId>
                  <version>${javacc.csharp.version}</version>
                  <!--                  <scope>runtime</scope>-->
                </dependency>
              </dependencies>
            </plugin>
          </plugins>
        </pluginManagement>
        <plugins>
          <plugin>
            <groupId>org.javacc.plugin</groupId>
            <artifactId>javacc-maven-plugin</artifactId>
            <executions>
              <execution>
                <id>jjt8wjjt</id>
                <phase>generate-sources</phase>
                <goals>
                  <goal>jjtree-javacc</goal>
                </goals>
                <configuration>
                  <outputDirectory>target/generated-sources/java</outputDirectory>
                  <sourceDirectory>src/main/jjtree</sourceDirectory>
                  <nodeDirectory>src/main/java</nodeDirectory>
                </configuration>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>${maven-compiler-plugin.version}</version>
            <dependencies>
              <dependency>
                <groupId>org.codehaus.plexus</groupId>
                <artifactId>plexus-compiler-csharp</artifactId>
                <version>${plexus-compiler-csharp.version}</version>
              </dependency>
            </dependencies>
            <configuration>
              <compilerId>csharp</compilerId>
              <verbose>true</verbose>
              <fork>true</fork>
              <!-- compilerArguments raises a depecation warning but works, compilerArgs does not -->
              <compilerArguments>
                <nologo>true</nologo>
                <target>exe</target>
                <out>${project.artifactId}.exe</out>
                <!--  unfortunately compiler options PreferredUILang & Utf8Output not supported
                https://github.com/codehaus-plexus/plexus-compiler/blob/plexus-compiler-2.15.0/plexus-compilers/plexus-compiler-csharp/src/main/java/org/codehaus/plexus/compiler/csharp/CSharpCompiler.java-->
              </compilerArguments>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>

    <profile>
      <!-- maven-compiler-plugin with plexus-compiler-csharp:  2024/07
           they assume the path to csc.exe is in the %PATH%;
           if it is not the case, set a new environment variable CscCompilerDir to this path
            (use dir /s %windir%\csc.exe and dir /s "%programfiles%\csc.exe"),
            so this profile will be activated and pick it to set the path to the executable  -->
      <id>csc-dir-env</id>
      <activation>
        <property>
          <name>env.CSCCOMPILERDIR</name>
        </property>
      </activation>
      <build>
        <pluginManagement>
          <plugins>
            <plugin>
              <groupId>org.apache.maven.plugins</groupId>
              <artifactId>maven-compiler-plugin</artifactId>
              <version>${maven-compiler-plugin.version}</version>
              <dependencies>
                <dependency>
                  <groupId>org.codehaus.plexus</groupId>
                  <artifactId>plexus-compiler-csharp</artifactId>
                  <version>${plexus-compiler-csharp.version}</version>
                  <!--                  <scope>runtime</scope>-->
                </dependency>
              </dependencies>
            </plugin>
          </plugins>
        </pluginManagement>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <dependencies>
              <dependency>
                <groupId>org.codehaus.plexus</groupId>
                <artifactId>plexus-compiler-csharp</artifactId>
                <version>${plexus-compiler-csharp.version}</version>
              </dependency>
            </dependencies>
            <configuration>
              <verbose>true</verbose>
              <compilerId>csharp</compilerId>
              <fork>true</fork>
              <executable>${env.CSCCOMPILERDIR}\csc.exe</executable>
              <!-- compilerArguments raises a depecation warning but works, compilerArgs does not -->
              <compilerArguments>
                <nologo>true</nologo>
                <target>exe</target>
                <out>${project.artifactId}.exe</out>
              </compilerArguments>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>

  </profiles>
</project>