options
{
  SANITY_CHECK = false;
  DEBUG_PARSER = true;
  DEBUG_TOKEN_MANAGER = true;
  DEBUG_LOOKAHEAD = true;
  STATIC = false;
  //NO_DFA=false;
}

PARSER_BEGIN(Bug)

PARSER_END(Bug)

SKIP : { " " | "\t" | "\n" | "\r" }

TOKEN :
{
  < LBRACKET : "[" >
| < RBRACKET : "]" >
| < LBRACE : "{" >
| < RBRACE : "}" >
| < LPAREN : "(" >
| < RPAREN : ")" >
}

TOKEN :
{
  < #UPPER : ["A"-"Z"] > 
| < #LOWER : ["a"-"z"] > 
| < #DIGIT : ["0"-"9"] > 
| < NUMBER : ( "0" | ["1"-"9"] ( < DIGIT > )*) > 
| < #LOWERCASEFIRST : < LOWER > ( "-" ( < LOWER > | < UPPER > | < DIGIT > ) | ( < LOWER > | < UPPER > | < DIGIT > ) )* > 
| < #UPPERCASEFIRST : < UPPER > ( "-" ( < LOWER > | < UPPER > | < DIGIT > ) | ( < LOWER > | < UPPER > | < DIGIT > ) )* >
}

TOKEN :
{
  < IDENTIFIANT : < LOWERCASEFIRST > >
| < VALUEREFERENCE : < LOWERCASEFIRST > >
}

void EnumerationItem() :
{}
{
  < LBRACE >
  (
    LOOKAHEAD(2)
    NamedNumber()
  | identifier()
  )
  < RBRACE >
}

void NamedNumber() :
{}
{
  (
    identifier()
  | valuereference()
  )
  < LPAREN > < NUMBER > < RPAREN >
}

void identifier() :
{}
{
  < IDENTIFIANT >
}

void valuereference() :
{}
{
  < VALUEREFERENCE >
}
