options
{
  SANITY_CHECK = false;
  DEBUG_PARSER = true;
  DEBUG_TOKEN_MANAGER = true;
  DEBUG_LOOKAHEAD = true;
  STATIC = false;
//  NO_DFA=true; // test
//  PARSER_INCLUDE = "stdio.h"; // test
//  TOKEN_MANAGER_INCLUDE = "<stdio.h>"; // test
//  TOKEN_INCLUDE = "<stdio.h>"; // test
  NAMESPACE = "mns";
//  BUILD_PARSER = false; // test
//  BUILD_TOKEN_MANAGER = false; // test
}

PARSER_BEGIN(Bug)

PARSER_END(Bug)

TOKEN_MGR_DECLS : {
  int mytmdels; // test
}

SKIP : { " " | "\t" | "\n" | "\r" }

TOKEN :
{
  < LBRACKET : "[" >
| < RBRACKET : "]" >
| < LBRACE : "{" >
| < RBRACE : "}" >
| < LPAREN : "(" >
| < RPAREN : ")" >
}

TOKEN :
{
  < #UPPER : ["A"-"Z"] > 
| < #LOWER : ["a"-"z"] > 
| < #DIGIT : ["0"-"9"] > 
| < NUMBER : ( "0" | ["1"-"9"] ( < DIGIT > )*) > 
| < #LOWERCASEFIRST : < LOWER > ( "-" ( < LOWER > | < UPPER > | < DIGIT > ) | ( < LOWER > | < UPPER > | < DIGIT > ) )* > 
| < #UPPERCASEFIRST : < UPPER > ( "-" ( < LOWER > | < UPPER > | < DIGIT > ) | ( < LOWER > | < UPPER > | < DIGIT > ) )* >
}

TOKEN :
{
  < IDENTIFIANT : < LOWERCASEFIRST > >
| < VALUEREFERENCE : < LOWERCASEFIRST > >
}
// e
/* ee */
/** eee */
void EnumerationItem() :
{}
{
  < LBRACE >
  (
    LOOKAHEAD(2)
    NamedNumber()
  | identifier()
  )
  < RBRACE >
}

// n

/** nnn */
void NamedNumber() :
{}
{
  (
    identifier()
  | valuereference()
  )
  < LPAREN > < NUMBER > < RPAREN >
}
// i
void identifier() :
{}
{
  < IDENTIFIANT >
}

void valuereference() :
{}
{
  < VALUEREFERENCE >
}
