/*
 * Copyright (c) 2020-2025, Sreeni Viswanadha <sreeni@viswanadha.net>.
 * Copyright (c) 2024-2025, Marc Mazas <mazas.marc@gmail.com>.
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 *     * Redistributions of source code must retain the above copyright notice,
 *       this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of the Sun Microsystems, Inc. nor the names of its
 *       contributors may be used to endorse or promote products derived from
 *       this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */
options
{
  STATIC = true; // JavaCC's default; not the same as Digest
  NAMESPACE = "FAQ";
}

PARSER_BEGIN(Faq)
// ugly hack to make javacc generate under a subdirectory
// package faq;

  static int count = FaqMain.count;
  static int beginAt = FaqMain.beginAt;
  static System.String outdir = FaqMain.outdir;
  static System.IO.StreamWriter indexsw = FaqMain.indexsw;

PARSER_END(Faq)

void MailFile() :
{ System.Console.Out.Write("Faq: "); }
{
  (
    { count++; }
    MailMessage()
    { System.Console.Out.Write(count + ". "); }
  )*
  <EOF>
  {
    System.Console.Out.WriteLine("");
    indexsw.Close();
  }
}

void MailMessage() :
{
  System.IO.StreamWriter msgsw = null;
  Token subj = null, from = null, date = null, body;
  if (count >= beginAt) {
    try {
      msgsw = new System.IO.StreamWriter(outdir + "/" + count + ".out.html");
    } catch (System.IO.IOException e) {
      System.Console.Error.WriteLine("IOE on " +outdir + "/" + count + ".out.html");
      System.Console.Error.WriteLine(System.Environment.StackTrace);
      System.Environment.Exit(4);
    }
  } else {
    System.Console.Error.WriteLine("count (" + count + ") < beginAt (" + beginAt + ")");
    return;
  }
}
{
  ( subj = <SUBJECT> | from = <FROM> | date = <DATE> )+
  {
    indexsw.Write("<a href=\"" + count + ".html\">");
    if (subj == null) {
      indexsw.WriteLine("no subject</a><br>");
    } else {
      indexsw.WriteLine(FaqMain.fix(subj.image) + "</a><br>");
    }
    if (count >= beginAt) {
      msgsw.WriteLine("<title>" + ((subj==null) ? "no subject" : FaqMain.fix(subj.image)) + "</title>");
      msgsw.WriteLine("Subject: " + ((subj==null) ? "no subject" : FaqMain.fix(subj.image)) + "<br>");
      msgsw.WriteLine("From: " + ((from==null) ? "" : FaqMain.fix(from.image)) + "<br>");
      msgsw.WriteLine("Date: " + ((date==null) ? "" : FaqMain.fix(date.image)) + "<br>");
      msgsw.WriteLine("<br>");
    }
  }
  (
    body = <BODY>
    {
      if (count >= beginAt) {
        msgsw.Write(FaqMain.fix(body.image) + "<br>");
      }
    }
  )*
  <END>
  {
    if (count >= beginAt) {
      msgsw.Close();
    }
  }
}

TOKEN:
{
  <#EOL: "\n" | "\r" | "\r\n">
|
  <#TWOEOLS: (("\n"|"\r\n") <EOL>) | ("\r\r" [ "\n" ])>
|
  <#NOT_EOL: ~["\n","\r"]>
}

<DEFAULT>
SKIP:
{
  < <EOL> "*** EOOH ***" <EOL> > : MAILHEADER
|
  <~[]>
}

<MAILHEADER>
SKIP:
{
  <_TWOEOLS: <TWOEOLS>> : MAILBODY
    // We cannot have just a reference to a regular expression in a
    // lexical specification - i.e., we cannot simply have <TWOEOLS>.
|
  "Subject: " : MAILSUBJECT
|
  "From: " : MAILFROM
|
  "Date: " : MAILDATE
|
  <~[]>
}

<MAILSUBJECT>
TOKEN:
{
  <SUBJECT: ( <NOT_EOL> )+>
}

<MAILSUBJECT>
SKIP:
{
  <_EOL1: <EOL>> : MAILHEADER
}

<MAILFROM>
TOKEN:
{
  <FROM: ( <NOT_EOL> )+>
}

<MAILFROM>
SKIP:
{
  <_EOL2: <EOL>> : MAILHEADER
}

<MAILDATE>
TOKEN:
{
  <DATE: ( <NOT_EOL> )+>
}

<MAILDATE>
SKIP:
{
  <_EOL3: <EOL>> : MAILHEADER
}

<MAILBODY>
TOKEN:
{
  <BODY: (~["\n","\r","\u001f"])* <EOL>>
|
  <END: "\u001f"> : DEFAULT
}
