options {
  DEBUG_TOKEN_MANAGER=true;
}

PARSER_BEGIN(ComplexLineComment)

PARSER_END(ComplexLineComment)

SKIP : { " " | "\t" | "\n" | "\r" }

TOKEN :
{
   <#NA : ~[ "-", "\r", "\n" ] >
| <#EOL : ( "\n" | "\r" | "\r\n" ) >
}

SPECIAL_TOKEN :
{
  "--" : LineComment
}

< LineComment >
SPECIAL_TOKEN :
{
  < (
      < NA >
    | "-" < NA >
    )*
    (
      < EOL >
    | "-" < EOL >
    | "-" "-"
    )? > : DEFAULT
}

TOKEN :
{
  < Id : [ "a"-"z", "A"-"Z" ] ( [ "a"-"z", "A"-"Z", "0"-"9", "-" ] )* >
  { System.Console.Out.WriteLine(matchedToken.ToString()); }
}

void Input() :
{}
{
  ( <Id> )*
  // { System.Console.Out.WriteLine("Finished ID+"); System.Console.Error.WriteLine("Finished ID+"); }
  <EOF>
  // { System.Console.Out.WriteLine("EOF found"); System.Console.Error.WriteLine("EOF found"); }
}
